source 'https://github.com/CocoaPods/Specs.git'

target 'TAlertView', :exclusive => true do
  pod "TAlertView", :path => "../"
end

target 'Tests', :exclusive => true do
  pod "TAlertView", :path => "../"

  pod 'Specta', '~> 0.2.1'
  pod 'Expecta'
  pod 'FBSnapshotTestCase'
  pod 'Expecta+Snapshots'
end
